version: 2 
  
jobs: 
  build: 
    docker: 
      - image: circleci/node:latest 
    steps: 
      - checkout 
      - run:
        name: Install Dependencies 
        command: . build/install.sh 
      - run: 
        name: Create Scratch Org 
        command: . build/create-scratch-org.sh 
      - run: 
        name: Validate Components & Run Tests 
        command: . build/test.sh 
      - store_test_results: 
        path: test-results 
          
  uatpackage-Install:
    docker:
     - image: circleci/node:latest
    steps:
      - checkout
      - run:
        name: Install Dependencies
        command: . build/install.sh
      - run:
        name: Login to UAT
        command: . build/setup-uat.sh
      - run:
        name: Install Package To UAT
        command: . build/uatpackage-Install.sh
        
workflows:
  version: 2
  validate:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
                - UAT
                - PkgBranch

      - uatpackage-Install:
           filters:
            branches:
              only:
                - PkgBranch